### ISSUE TITLE
Ideas for the ObjectManager class/Object refactor.

### ISSUE THREAD

**Issue by wshearn** [ArchaicMage/Leadwerks-Template#2]
With the object manager we should enable scripters(artists, gameplay programmers, etc) to use base classes with out having to do any C++ coding.
Leadwerks has LUA intergration built in(Leadwerks::Interpreter)

Object refactor:
    - Object becomes a generic class in which we can have a common base class for just about anything.
        -- This will allow global options
            --- EX: PrintDebug that when called from and object it will print a serialized dump of the object. (Just an example, no plans to add it)
    - Move _PLACABLE_ GameObjects to Actor class(ala Unreal Engine style)
        -- Define sound, model, movement, health(see above and AActor API reference from UnrealEngine) etc
        -- Reference:
            --- https://docs.unrealengine.com/latest/INT/API/Runtime/CoreUObject/UObject/UObject/index.html
            --- https://docs.unrealengine.com/latest/INT/API/Runtime/Engine/GameFramework/AActor/index.html
        -- Add common triggers
            --- Player collision, destroyed, etc
    - Move Camera to PlayerController(Child of Actor)
        -- Create FPS, TPS, Flight playeractor classes as child of PlayerController

ObjectManager:
    - Load actors scripts(references game actors,) -> Scripts/Objects/_RegisterBinaryActors.lua
        -- _RegisterBinaryObjects references other lua files
        -- Other lua files contains needed info for model, sounds, movement(rotating each tick, think spinning pickups ala Quake style)
        -- Reason for defining Actors is so that people can place them in a map and we can hook the map loading and we can replace the item during loading.
            --- Benifits is we can create a proper load screen as we will load the objects ourselves and not just a glob of a single map.
                ---- Yes, leadwerks loads maps fast but if the dev tries to scale out it may slow down and cause a bad exp for the end user
            --- We can release items that are no longer needed during a cleanup task(say a barrel got blown up and the index counter reached 0, we can safely unload it)
            --- This also allows developers to create a simple base layout of all the items with ease and allow the artist to get in and see the(uncoded)
                items with their proper models as it would inherit that properity from Actor

**Comment by wyldmagic-joshua** [comment]
Hey Wshearn, I am very sorry for the late response. I was out of town for the holidays with limited access to a computer and I just saw your merge request along with your refactor thoughts. I have actually refactored the object system into a data-driven entity component system. The component system is completely modular, removing the inheritance-based game object structure. Each individual component, of which there are several, provide a higher-level abstraction over Leadwerks specific implementations. This will allow game objects to be `constructed` from multiple components. This component system can easily be consumed by Lua, allowing mechanics and gameplay to be defined within Lua scripts while utilizing the low-level properties/methods within the components themselves for simplification. I have all of this implemented within a sandbox environment and will be incorporating the changes over the next few months.

This integration effort will also introduce a number of other changes and enhancements to the Leadwerks template, cleaning up implementations, separating the application from the underlying Leadwerks framework, networking, scene management and several others. The template also sees a movement towards dependency injection and the use of interfaces.

How familiar are you with best-practices when it comes to incorporating Lua into a c++ applications?  I would greatly appreciate offloading Lua incorporation to someone who has the knowledge and passion to merge the two technologies in a clean and efficient manner.

**Comment by wshearn** [comment]
I am not familiar with "best-practices".

Since C++ really doesn't have any metadata that we can query(ie get all methods/variables in a class) I don't know of a simple way to handle this.(So we can map class to lua data type so it can be called from a LUA script, see http://www.lua.org/pil/28.3.html)

Unreal Engine 4 handles this by having their own utility that parses headers for C++ macros(they are empty defines so they are ignored by the compiler) then it generates a seperate header file with all the needed items(ie luaL_reg). IMO this is a messy way to handle it but AFAIK one of the few ways to do it.

I know C++11 has custom attributes but I am not sure if they are powerful enough to handle this.

**Comment by wyldmagic-joshua** [comment]
Hey wshearn, I am unsure if you are still looking to using this project but I have a somewhat stable release with the modifications I have been working on over the last few months. It contains a working entity component system with interfaces into using Lua script.

Currently, the Lua implementation allows scripts to be used as configs for components however, this will be expanded over the next few months. I am looking to get some exposure to into the project in order to make well adjusted modifications based on user feedback.

**Comment by wshearn** [comment]
I will give it another look. But you see what I mean by having to have the LUA vars hard coded into C++? I really wonder if there is a better way to handle that.
